# Branch protection rules for main and develop branches

rules:
  # Main branch protection
  main:
    required_status_checks:
      strict: true
      contexts:
        - "CI / Build"
        - "CI / Test"
        - "CI / Lint"
        - "Security Scan"
    enforce_admins: true
    required_pull_request_reviews:
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      required_approving_review_count: 1
    restrictions:
      users: []
      teams: []
      apps: []
    required_linear_history: true
    allow_force_pushes: false
    allow_deletions: false

  # Develop branch protection
  develop:
    required_status_checks:
      strict: true
      contexts:
        - "CI / Build"
        - "CI / Test"
        - "CI / Lint"
    enforce_admins: false
    required_pull_request_reviews:
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      required_approving_review_count: 1
    restrictions:
      users: []
      teams: []
      apps: []
    required_linear_history: true
    allow_force_pushes: false
    allow_deletions: false
