"""Repository for ComplianceReport model."""

from typing import List, Optional

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from ..models.compliance_report import ComplianceReport
from .base_repository import BaseRepository


class ComplianceReportRepository(BaseRepository[ComplianceReport]):
    """Repository for managing compliance reports.

    Provides CRUD operations and specialized queries for compliance reports
    including filtering by project, code type, and status.
    """

    def __init__(self, db_session: AsyncSession):
        """Initialize repository with session.

        Args:
            db_session: Async database session
        """
        super().__init__(ComplianceReport, db_session)

    async def get_by_project_id(self, project_id: str) -> List[ComplianceReport]:
        """Get all compliance reports for a project.

        Args:
            project_id: Project identifier

        Returns:
            List of compliance reports
        """
        return await self.filter_by(project_id=project_id)

    async def get_by_code_type(self, code_type: str) -> List[ComplianceReport]:
        """Get compliance reports by code type.

        Args:
            code_type: Type of code (structural, mep, energy, fire)

        Returns:
            List of compliance reports
        """
        return await self.filter_by(code_type=code_type)

    async def get_by_project_and_code_type(
        self, project_id: str, code_type: str
    ) -> List[ComplianceReport]:
        """Get compliance reports by project and code type.

        Args:
            project_id: Project identifier
            code_type: Type of code

        Returns:
            List of compliance reports
        """
        return await self.filter_by(project_id=project_id, code_type=code_type)

    async def get_by_calculation_sheet_id(
        self, calculation_sheet_id: int
    ) -> List[ComplianceReport]:
        """Get compliance reports linked to a calculation sheet.

        Args:
            calculation_sheet_id: Calculation sheet ID

        Returns:
            List of compliance reports
        """
        return await self.filter_by(calculation_sheet_id=calculation_sheet_id)

    async def get_by_overall_status(
        self, overall_status: str
    ) -> List[ComplianceReport]:
        """Get compliance reports by overall status.

        Args:
            overall_status: Overall status (compliant, non_compliant, review_required)

        Returns:
            List of compliance reports
        """
        return await self.filter_by(overall_status=overall_status)

    async def get_by_jurisdiction(self, jurisdiction: str) -> List[ComplianceReport]:
        """Get compliance reports by jurisdiction.

        Args:
            jurisdiction: Jurisdiction name

        Returns:
            List of compliance reports
        """
        return await self.filter_by(jurisdiction=jurisdiction)

    async def get_by_generated_by(self, user_id: str) -> List[ComplianceReport]:
        """Get compliance reports generated by a user.

        Args:
            user_id: User identifier

        Returns:
            List of compliance reports
        """
        return await self.filter_by(generated_by=user_id)

    async def search_by_title(self, search_term: str) -> List[ComplianceReport]:
        """Search compliance reports by title.

        Args:
            search_term: Search term to match in title

        Returns:
            List of matching compliance reports
        """
        query = select(ComplianceReport).where(
            ComplianceReport.title.ilike(f"%{search_term}%")
        )

        result = await self.db_session.execute(query)
        return list(result.scalars().all())

    async def get_recent(self, limit: int = 10) -> List[ComplianceReport]:
        """Get most recent compliance reports.

        Args:
            limit: Maximum number of reports to return

        Returns:
            List of recent compliance reports
        """
        query = (
            select(ComplianceReport)
            .order_by(ComplianceReport.generated_at.desc())
            .limit(limit)
        )

        result = await self.db_session.execute(query)
        return list(result.scalars().all())

    async def get_non_compliant_reports(
        self, project_id: Optional[str] = None
    ) -> List[ComplianceReport]:
        """Get non-compliant reports, optionally filtered by project.

        Args:
            project_id: Optional project identifier to filter by

        Returns:
            List of non-compliant reports
        """
        filters = {"overall_status": "non_compliant"}
        if project_id:
            filters["project_id"] = project_id

        return await self.filter_by(**filters)

    async def get_pending_review_reports(
        self, project_id: Optional[str] = None
    ) -> List[ComplianceReport]:
        """Get reports pending review, optionally filtered by project.

        Args:
            project_id: Optional project identifier to filter by

        Returns:
            List of reports pending review
        """
        filters = {"overall_status": "review_required"}
        if project_id:
            filters["project_id"] = project_id

        return await self.filter_by(**filters)
