"""initial_labor_service_schema

Revision ID: 6325453507b3
Revises:
Create Date: 2025-11-14 18:42:55.341353

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6325453507b3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_providers",
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="Reference to user in User Service",
        ),
        sa.Column(
            "business_name",
            sa.String(length=255),
            nullable=True,
            comment="Business name (for business providers)",
        ),
        sa.Column(
            "individual_name",
            sa.String(length=255),
            nullable=False,
            comment="Individual or contact person name",
        ),
        sa.Column(
            "provider_type",
            sa.Enum("INDIVIDUAL", "BUSINESS", "TEAM", name="providertype"),
            nullable=False,
            comment="Type of provider",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Provider description and bio",
        ),
        sa.Column(
            "experience_years",
            sa.Integer(),
            nullable=False,
            comment="Years of experience",
        ),
        sa.Column(
            "verification_status",
            sa.Enum(
                "PENDING",
                "VERIFIED",
                "REJECTED",
                "SUSPENDED",
                name="verificationstatus",
            ),
            nullable=False,
            comment="Verification status",
        ),
        sa.Column(
            "verification_date",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Date of verification",
        ),
        sa.Column(
            "rating",
            sa.Numeric(precision=3, scale=2),
            nullable=False,
            comment="Average rating (0.00-5.00)",
        ),
        sa.Column(
            "total_reviews",
            sa.Integer(),
            nullable=False,
            comment="Total number of reviews",
        ),
        sa.Column(
            "total_jobs_completed",
            sa.Integer(),
            nullable=False,
            comment="Total jobs completed",
        ),
        sa.Column(
            "response_time_avg",
            sa.Integer(),
            nullable=False,
            comment="Average response time in minutes",
        ),
        sa.Column(
            "insurance_info",
            sa.JSON(),
            nullable=True,
            comment="Insurance information (JSON)",
        ),
        sa.Column(
            "portfolio_images",
            sa.JSON(),
            nullable=True,
            comment="Portfolio image URLs (JSON array)",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Provider active status"
        ),
        sa.Column(
            "is_available",
            sa.Boolean(),
            nullable=False,
            comment="Current availability status",
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Primary key",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record creation timestamp",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record last update timestamp",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        "idx_active_available",
        "service_providers",
        ["is_active", "is_available"],
        unique=False,
    )
    op.create_index(
        "idx_provider_type", "service_providers", ["provider_type"], unique=False
    )
    op.create_index("idx_rating", "service_providers", ["rating"], unique=False)
    op.create_index("idx_user_id", "service_providers", ["user_id"], unique=False)
    op.create_index(
        "idx_verification_status",
        "service_providers",
        ["verification_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_providers_created_at"),
        "service_providers",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_providers_updated_at"),
        "service_providers",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "service_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("seeker_id", sa.Integer(), nullable=False),
        sa.Column("location_address", sa.String(length=500), nullable=False),
        sa.Column(
            "location_latitude", sa.Numeric(precision=10, scale=8), nullable=True
        ),
        sa.Column(
            "location_longitude", sa.Numeric(precision=11, scale=8), nullable=True
        ),
        sa.Column("budget_min", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("budget_max", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("budget_currency", sa.String(length=3), nullable=False),
        sa.Column(
            "urgency_level",
            sa.Enum("LOW", "MEDIUM", "HIGH", "EMERGENCY", name="urgencylevel"),
            nullable=False,
        ),
        sa.Column("preferred_start_date", sa.DateTime(), nullable=True),
        sa.Column("estimated_duration_hours", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "QUOTED",
                "BOOKED",
                "COMPLETED",
                "CANCELLED",
                name="requeststatus",
            ),
            nullable=False,
        ),
        sa.Column("requirements", sa.JSON(), nullable=True),
        sa.Column("images", sa.JSON(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_budget_range_status",
        "service_requests",
        ["budget_min", "budget_max", "status"],
        unique=False,
    )
    op.create_index(
        "idx_expires_status", "service_requests", ["expires_at", "status"], unique=False
    )
    op.create_index(
        "idx_location_coords",
        "service_requests",
        ["location_latitude", "location_longitude"],
        unique=False,
    )
    op.create_index(
        "idx_location_urgency",
        "service_requests",
        ["location_latitude", "location_longitude", "urgency_level"],
        unique=False,
    )
    op.create_index(
        "idx_project_status", "service_requests", ["project_id", "status"], unique=False
    )
    op.create_index(
        "idx_seeker_status", "service_requests", ["seeker_id", "status"], unique=False
    )
    op.create_index(
        "idx_status_created", "service_requests", ["status", "created_at"], unique=False
    )
    op.create_index(
        "idx_urgency_created",
        "service_requests",
        ["urgency_level", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_requests_id"), "service_requests", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_service_requests_project_id"),
        "service_requests",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_requests_seeker_id"),
        "service_requests",
        ["seeker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_requests_title"), "service_requests", ["title"], unique=False
    )
    op.create_table(
        "skill_categories",
        sa.Column(
            "name", sa.String(length=100), nullable=False, comment="Category name"
        ),
        sa.Column(
            "description", sa.Text(), nullable=True, comment="Category description"
        ),
        sa.Column(
            "sort_order", sa.Integer(), nullable=False, comment="Display sort order"
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Category active status"
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Primary key",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record creation timestamp",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record last update timestamp",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_skill_categories_created_at"),
        "skill_categories",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_skill_categories_updated_at"),
        "skill_categories",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "quotes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("labor_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("material_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("travel_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("start_availability", sa.DateTime(), nullable=False),
        sa.Column("completion_estimate", sa.DateTime(), nullable=False),
        sa.Column("estimated_hours", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("terms_and_conditions", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "ACCEPTED",
                "REJECTED",
                "EXPIRED",
                "WITHDRAWN",
                name="quotestatus",
            ),
            nullable=False,
        ),
        sa.Column("valid_until", sa.DateTime(), nullable=False),
        sa.Column("cost_breakdown_details", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["request_id"], ["service_requests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_cost_range_status", "quotes", ["total_cost", "status"], unique=False
    )
    op.create_index(
        "idx_provider_status_created",
        "quotes",
        ["provider_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_request_provider", "quotes", ["request_id", "provider_id"], unique=False
    )
    op.create_index(
        "idx_request_status_cost",
        "quotes",
        ["request_id", "status", "total_cost"],
        unique=False,
    )
    op.create_index(
        "idx_status_expiration", "quotes", ["status", "valid_until"], unique=False
    )
    op.create_index(
        "idx_submitted_date", "quotes", ["submitted_at", "status"], unique=False
    )
    op.create_index(
        "idx_unique_active_quote",
        "quotes",
        ["request_id", "provider_id", "status"],
        unique=True,
        postgresql_where="status IN ('DRAFT', 'SUBMITTED')",
    )
    op.create_index(op.f("ix_quotes_id"), "quotes", ["id"], unique=False)
    op.create_index(
        op.f("ix_quotes_provider_id"), "quotes", ["provider_id"], unique=False
    )
    op.create_index(
        op.f("ix_quotes_request_id"), "quotes", ["request_id"], unique=False
    )
    op.create_table(
        "service_areas",
        sa.Column(
            "provider_id",
            sa.Integer(),
            nullable=False,
            comment="Reference to service provider",
        ),
        sa.Column(
            "center_latitude",
            sa.Numeric(precision=10, scale=8),
            nullable=False,
            comment="Center latitude coordinate",
        ),
        sa.Column(
            "center_longitude",
            sa.Numeric(precision=11, scale=8),
            nullable=False,
            comment="Center longitude coordinate",
        ),
        sa.Column(
            "radius_miles",
            sa.Integer(),
            nullable=False,
            comment="Service radius in miles",
        ),
        sa.Column(
            "travel_rate",
            sa.Numeric(precision=8, scale=2),
            nullable=True,
            comment="Travel rate per mile",
        ),
        sa.Column(
            "area_name",
            sa.String(length=255),
            nullable=True,
            comment="Friendly name for service area",
        ),
        sa.Column(
            "is_primary",
            sa.Boolean(),
            nullable=False,
            comment="Whether this is the primary service area",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Service area active status",
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Primary key",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record creation timestamp",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record last update timestamp",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["service_providers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_service_area_active", "service_areas", ["is_active"], unique=False
    )
    op.create_index(
        "idx_service_area_location",
        "service_areas",
        ["center_latitude", "center_longitude"],
        unique=False,
    )
    op.create_index(
        "idx_service_area_primary", "service_areas", ["is_primary"], unique=False
    )
    op.create_index(
        "idx_service_area_provider_id", "service_areas", ["provider_id"], unique=False
    )
    op.create_index(
        op.f("ix_service_areas_created_at"),
        "service_areas",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_areas_updated_at"),
        "service_areas",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "skill_requirements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_request_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("proficiency_level", sa.String(length=20), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("importance_weight", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_request_id"], ["service_requests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_skill_requirements_id"), "skill_requirements", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_skill_requirements_service_request_id"),
        "skill_requirements",
        ["service_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_skill_requirements_skill_id"),
        "skill_requirements",
        ["skill_id"],
        unique=False,
    )
    op.create_table(
        "skills",
        sa.Column(
            "category_id",
            sa.Integer(),
            nullable=False,
            comment="Reference to skill category",
        ),
        sa.Column("name", sa.String(length=100), nullable=False, comment="Skill name"),
        sa.Column("description", sa.Text(), nullable=True, comment="Skill description"),
        sa.Column(
            "requires_certification",
            sa.Boolean(),
            nullable=False,
            comment="Whether skill requires certification",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Skill active status"
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Primary key",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record creation timestamp",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record last update timestamp",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["skill_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_category_id", "skills", ["category_id"], unique=False)
    op.create_index(
        "idx_requires_cert", "skills", ["requires_certification"], unique=False
    )
    op.create_index("idx_skill_name", "skills", ["name"], unique=False)
    op.create_index(
        op.f("ix_skills_created_at"), "skills", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_skills_updated_at"), "skills", ["updated_at"], unique=False
    )
    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_request_id", sa.Integer(), nullable=False),
        sa.Column("quote_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("scheduled_start_date", sa.DateTime(), nullable=False),
        sa.Column("scheduled_completion_date", sa.DateTime(), nullable=False),
        sa.Column("actual_start_date", sa.DateTime(), nullable=True),
        sa.Column("actual_completion_date", sa.DateTime(), nullable=True),
        sa.Column("total_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("payment_terms", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "CONFIRMED",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                "DISPUTED",
                name="bookingstatus",
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["quote_id"], ["quotes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["service_request_id"], ["service_requests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_active_schedule",
        "bookings",
        ["scheduled_start_date", "scheduled_completion_date"],
        unique=False,
        postgresql_where="status IN ('CONFIRMED', 'IN_PROGRESS')",
    )
    op.create_index(
        "idx_booking_status_created", "bookings", ["status", "created_at"], unique=False
    )
    op.create_index(
        "idx_client_status_schedule",
        "bookings",
        ["client_id", "status", "scheduled_start_date"],
        unique=False,
    )
    op.create_index(
        "idx_provider_status_schedule",
        "bookings",
        ["provider_id", "status", "scheduled_start_date"],
        unique=False,
    )
    op.create_index(
        "idx_quote_booking", "bookings", ["quote_id", "status"], unique=False
    )
    op.create_index(
        "idx_schedule_range",
        "bookings",
        ["scheduled_start_date", "scheduled_completion_date", "status"],
        unique=False,
    )
    op.create_index(
        "idx_service_request_booking",
        "bookings",
        ["service_request_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bookings_client_id"), "bookings", ["client_id"], unique=False
    )
    op.create_index(op.f("ix_bookings_id"), "bookings", ["id"], unique=False)
    op.create_index(
        op.f("ix_bookings_provider_id"), "bookings", ["provider_id"], unique=False
    )
    op.create_index(
        op.f("ix_bookings_quote_id"), "bookings", ["quote_id"], unique=False
    )
    op.create_index(
        op.f("ix_bookings_service_request_id"),
        "bookings",
        ["service_request_id"],
        unique=False,
    )
    op.create_table(
        "provider_skills",
        sa.Column(
            "provider_id",
            sa.Integer(),
            nullable=False,
            comment="Reference to service provider",
        ),
        sa.Column(
            "skill_id", sa.Integer(), nullable=False, comment="Reference to skill"
        ),
        sa.Column(
            "proficiency_level",
            sa.Enum(
                "BEGINNER",
                "INTERMEDIATE",
                "ADVANCED",
                "EXPERT",
                name="proficiencylevel",
            ),
            nullable=False,
            comment="Provider's proficiency level in this skill",
        ),
        sa.Column(
            "years_experience",
            sa.Integer(),
            nullable=False,
            comment="Years of experience with this skill",
        ),
        sa.Column(
            "hourly_rate",
            sa.Numeric(precision=8, scale=2),
            nullable=True,
            comment="Hourly rate for this skill",
        ),
        sa.Column(
            "certifications",
            sa.JSON(),
            nullable=True,
            comment="Certifications for this skill (JSON array)",
        ),
        sa.Column(
            "is_primary",
            sa.Boolean(),
            nullable=False,
            comment="Whether this is a primary skill",
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Primary key",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record creation timestamp",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record last update timestamp",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["service_providers.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_provider_skill_primary", "provider_skills", ["is_primary"], unique=False
    )
    op.create_index(
        "idx_provider_skill_proficiency",
        "provider_skills",
        ["proficiency_level"],
        unique=False,
    )
    op.create_index(
        "idx_provider_skill_provider_id",
        "provider_skills",
        ["provider_id"],
        unique=False,
    )
    op.create_index(
        "idx_provider_skill_skill_id", "provider_skills", ["skill_id"], unique=False
    )
    op.create_index(
        op.f("ix_provider_skills_created_at"),
        "provider_skills",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_skills_updated_at"),
        "provider_skills",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        "unique_provider_skill",
        "provider_skills",
        ["provider_id", "skill_id"],
        unique=True,
    )
    op.create_table(
        "booking_milestones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "PAID",
                "DISPUTED",
                name="milestonestatus",
            ),
            nullable=False,
        ),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("completed_date", sa.DateTime(), nullable=True),
        sa.Column("paid_date", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("completion_evidence", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_booking_sequence",
        "booking_milestones",
        ["booking_id", "sequence_number"],
        unique=False,
    )
    op.create_index(
        "idx_booking_status_sequence",
        "booking_milestones",
        ["booking_id", "status", "sequence_number"],
        unique=False,
    )
    op.create_index(
        "idx_completed_date",
        "booking_milestones",
        ["completed_date", "status"],
        unique=False,
    )
    op.create_index(
        "idx_due_date_pending",
        "booking_milestones",
        ["due_date", "status"],
        unique=False,
        postgresql_where="status = 'PENDING'",
    )
    op.create_index(
        "idx_status_due_date",
        "booking_milestones",
        ["status", "due_date"],
        unique=False,
    )
    op.create_index(
        "idx_unique_booking_sequence",
        "booking_milestones",
        ["booking_id", "sequence_number"],
        unique=True,
    )
    op.create_index(
        op.f("ix_booking_milestones_booking_id"),
        "booking_milestones",
        ["booking_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_booking_milestones_id"), "booking_milestones", ["id"], unique=False
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("reviewer_id", sa.Integer(), nullable=False),
        sa.Column("reviewee_id", sa.Integer(), nullable=False),
        sa.Column(
            "review_type",
            sa.Enum("SEEKER_TO_PROVIDER", "PROVIDER_TO_SEEKER", name="reviewtype"),
            nullable=False,
        ),
        sa.Column("overall_rating", sa.Integer(), nullable=False),
        sa.Column("quality_rating", sa.Integer(), nullable=False),
        sa.Column("timeliness_rating", sa.Integer(), nullable=False),
        sa.Column("communication_rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("images", sa.JSON(), nullable=True),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("response_date", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PUBLISHED",
                "PENDING_MODERATION",
                "REJECTED",
                "HIDDEN",
                name="reviewstatus",
            ),
            nullable=False,
        ),
        sa.Column("moderated_at", sa.DateTime(), nullable=True),
        sa.Column("moderated_by", sa.Integer(), nullable=True),
        sa.Column("helpful_votes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_booking_type_status",
        "reviews",
        ["booking_id", "review_type", "status"],
        unique=False,
    )
    op.create_index(
        "idx_helpful_votes_status", "reviews", ["helpful_votes", "status"], unique=False
    )
    op.create_index(
        "idx_moderation_queue",
        "reviews",
        ["status", "created_at"],
        unique=False,
        postgresql_where="status = 'PENDING_MODERATION'",
    )
    op.create_index(
        "idx_review_status_rating_created",
        "reviews",
        ["status", "overall_rating", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_reviewee_type_status_rating",
        "reviews",
        ["reviewee_id", "review_type", "status", "overall_rating"],
        unique=False,
    )
    op.create_index(
        "idx_reviewer_type_created",
        "reviews",
        ["reviewer_id", "review_type", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_unique_booking_reviewer_type",
        "reviews",
        ["booking_id", "reviewer_id", "review_type"],
        unique=True,
    )
    op.create_index(
        op.f("ix_reviews_booking_id"), "reviews", ["booking_id"], unique=False
    )
    op.create_index(op.f("ix_reviews_id"), "reviews", ["id"], unique=False)
    op.create_index(
        op.f("ix_reviews_reviewee_id"), "reviews", ["reviewee_id"], unique=False
    )
    op.create_index(
        op.f("ix_reviews_reviewer_id"), "reviews", ["reviewer_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reviews_reviewer_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_reviewee_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_booking_id"), table_name="reviews")
    op.drop_index("idx_unique_booking_reviewer_type", table_name="reviews")
    op.drop_index("idx_reviewer_type_created", table_name="reviews")
    op.drop_index("idx_reviewee_type_status_rating", table_name="reviews")
    op.drop_index("idx_review_status_rating_created", table_name="reviews")
    op.drop_index(
        "idx_moderation_queue",
        table_name="reviews",
        postgresql_where="status = 'PENDING_MODERATION'",
    )
    op.drop_index("idx_helpful_votes_status", table_name="reviews")
    op.drop_index("idx_booking_type_status", table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_booking_milestones_id"), table_name="booking_milestones")
    op.drop_index(
        op.f("ix_booking_milestones_booking_id"), table_name="booking_milestones"
    )
    op.drop_index("idx_unique_booking_sequence", table_name="booking_milestones")
    op.drop_index("idx_status_due_date", table_name="booking_milestones")
    op.drop_index(
        "idx_due_date_pending",
        table_name="booking_milestones",
        postgresql_where="status = 'PENDING'",
    )
    op.drop_index("idx_completed_date", table_name="booking_milestones")
    op.drop_index("idx_booking_status_sequence", table_name="booking_milestones")
    op.drop_index("idx_booking_sequence", table_name="booking_milestones")
    op.drop_table("booking_milestones")
    op.drop_index("unique_provider_skill", table_name="provider_skills")
    op.drop_index(op.f("ix_provider_skills_updated_at"), table_name="provider_skills")
    op.drop_index(op.f("ix_provider_skills_created_at"), table_name="provider_skills")
    op.drop_index("idx_provider_skill_skill_id", table_name="provider_skills")
    op.drop_index("idx_provider_skill_provider_id", table_name="provider_skills")
    op.drop_index("idx_provider_skill_proficiency", table_name="provider_skills")
    op.drop_index("idx_provider_skill_primary", table_name="provider_skills")
    op.drop_table("provider_skills")
    op.drop_index(op.f("ix_bookings_service_request_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_quote_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_provider_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_client_id"), table_name="bookings")
    op.drop_index("idx_service_request_booking", table_name="bookings")
    op.drop_index("idx_schedule_range", table_name="bookings")
    op.drop_index("idx_quote_booking", table_name="bookings")
    op.drop_index("idx_provider_status_schedule", table_name="bookings")
    op.drop_index("idx_client_status_schedule", table_name="bookings")
    op.drop_index("idx_booking_status_created", table_name="bookings")
    op.drop_index(
        "idx_active_schedule",
        table_name="bookings",
        postgresql_where="status IN ('CONFIRMED', 'IN_PROGRESS')",
    )
    op.drop_table("bookings")
    op.drop_index(op.f("ix_skills_updated_at"), table_name="skills")
    op.drop_index(op.f("ix_skills_created_at"), table_name="skills")
    op.drop_index("idx_skill_name", table_name="skills")
    op.drop_index("idx_requires_cert", table_name="skills")
    op.drop_index("idx_category_id", table_name="skills")
    op.drop_table("skills")
    op.drop_index(
        op.f("ix_skill_requirements_skill_id"), table_name="skill_requirements"
    )
    op.drop_index(
        op.f("ix_skill_requirements_service_request_id"),
        table_name="skill_requirements",
    )
    op.drop_index(op.f("ix_skill_requirements_id"), table_name="skill_requirements")
    op.drop_table("skill_requirements")
    op.drop_index(op.f("ix_service_areas_updated_at"), table_name="service_areas")
    op.drop_index(op.f("ix_service_areas_created_at"), table_name="service_areas")
    op.drop_index("idx_service_area_provider_id", table_name="service_areas")
    op.drop_index("idx_service_area_primary", table_name="service_areas")
    op.drop_index("idx_service_area_location", table_name="service_areas")
    op.drop_index("idx_service_area_active", table_name="service_areas")
    op.drop_table("service_areas")
    op.drop_index(op.f("ix_quotes_request_id"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_provider_id"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_id"), table_name="quotes")
    op.drop_index(
        "idx_unique_active_quote",
        table_name="quotes",
        postgresql_where="status IN ('DRAFT', 'SUBMITTED')",
    )
    op.drop_index("idx_submitted_date", table_name="quotes")
    op.drop_index("idx_status_expiration", table_name="quotes")
    op.drop_index("idx_request_status_cost", table_name="quotes")
    op.drop_index("idx_request_provider", table_name="quotes")
    op.drop_index("idx_provider_status_created", table_name="quotes")
    op.drop_index("idx_cost_range_status", table_name="quotes")
    op.drop_table("quotes")
    op.drop_index(op.f("ix_skill_categories_updated_at"), table_name="skill_categories")
    op.drop_index(op.f("ix_skill_categories_created_at"), table_name="skill_categories")
    op.drop_table("skill_categories")
    op.drop_index(op.f("ix_service_requests_title"), table_name="service_requests")
    op.drop_index(op.f("ix_service_requests_seeker_id"), table_name="service_requests")
    op.drop_index(op.f("ix_service_requests_project_id"), table_name="service_requests")
    op.drop_index(op.f("ix_service_requests_id"), table_name="service_requests")
    op.drop_index("idx_urgency_created", table_name="service_requests")
    op.drop_index("idx_status_created", table_name="service_requests")
    op.drop_index("idx_seeker_status", table_name="service_requests")
    op.drop_index("idx_project_status", table_name="service_requests")
    op.drop_index("idx_location_urgency", table_name="service_requests")
    op.drop_index("idx_location_coords", table_name="service_requests")
    op.drop_index("idx_expires_status", table_name="service_requests")
    op.drop_index("idx_budget_range_status", table_name="service_requests")
    op.drop_table("service_requests")
    op.drop_index(
        op.f("ix_service_providers_updated_at"), table_name="service_providers"
    )
    op.drop_index(
        op.f("ix_service_providers_created_at"), table_name="service_providers"
    )
    op.drop_index("idx_verification_status", table_name="service_providers")
    op.drop_index("idx_user_id", table_name="service_providers")
    op.drop_index("idx_rating", table_name="service_providers")
    op.drop_index("idx_provider_type", table_name="service_providers")
    op.drop_index("idx_active_available", table_name="service_providers")
    op.drop_table("service_providers")
    # ### end Alembic commands ###
