"""Pydantic schemas for request/response validation."""

from .analysis import (AccessibilityCheckRequest, AccessibilityCheckResponse,
                       AccessibilityViolation, BuildingParameters,
                       ComplianceCheckRequest, ComplianceCheckResponse,
                       EfficiencyRecommendation, EnergyAnalysisRequest,
                       EnergyAnalysisResponse, EnergyEstimate, EnvelopeMetrics,
                       LayoutRecommendation, LoadCalculations, LoadParameters,
                       MaterialProperties, MaterialSpecificationRequest,
                       MaterialSpecificationResponse, PlanningConstraints,
                       RouteValidation, SpaceMetrics, SpacePlanningRequest,
                       SpacePlanningResponse, SpaceRequirement,
                       StructuralAnalysisRequest, StructuralAnalysisResponse,
                       StructuralIssue, VendorInfo, ViolationDetail,
                       WarningDetail)
from .base import (BaseSchema, ErrorDetail, ErrorResponse, LocationData,
                   PaginatedResponse, PaginationParams, TimestampMixin)
from .design import (CreateDesignRequest, DesignDetailResponse,
                     DesignListResponse, DesignResponse, DesignVersionResponse,
                     UpdateDesignRequest)
from .drawing import (DrawingDetailResponse, DrawingListResponse,
                      DrawingResponse, DrawingUploadRequest,
                      FileValidationError, validate_file_upload)
from .enums import (AnalysisType, BuildingType, CheckStatus,
                    ComplianceCheckType, DesignStatus, DrawingType,
                    MaterialCategory, OptimizationGoal, StructuralSystem)

__all__ = [
    # Base schemas
    "BaseSchema",
    "ErrorDetail",
    "ErrorResponse",
    "LocationData",
    "PaginatedResponse",
    "PaginationParams",
    "TimestampMixin",
    # Enums
    "AnalysisType",
    "BuildingType",
    "CheckStatus",
    "ComplianceCheckType",
    "DesignStatus",
    "DrawingType",
    "MaterialCategory",
    "OptimizationGoal",
    "StructuralSystem",
    # Design schemas
    "CreateDesignRequest",
    "DesignDetailResponse",
    "DesignListResponse",
    "DesignResponse",
    "DesignVersionResponse",
    "UpdateDesignRequest",
    # Drawing schemas
    "DrawingDetailResponse",
    "DrawingListResponse",
    "DrawingResponse",
    "DrawingUploadRequest",
    "FileValidationError",
    "validate_file_upload",
    # Analysis schemas
    "AccessibilityCheckRequest",
    "AccessibilityCheckResponse",
    "AccessibilityViolation",
    "BuildingParameters",
    "ComplianceCheckRequest",
    "ComplianceCheckResponse",
    "EfficiencyRecommendation",
    "EnergyAnalysisRequest",
    "EnergyAnalysisResponse",
    "EnergyEstimate",
    "EnvelopeMetrics",
    "LayoutRecommendation",
    "LoadCalculations",
    "LoadParameters",
    "MaterialProperties",
    "MaterialSpecificationRequest",
    "MaterialSpecificationResponse",
    "PlanningConstraints",
    "RouteValidation",
    "SpaceMetrics",
    "SpacePlanningRequest",
    "SpacePlanningResponse",
    "SpaceRequirement",
    "StructuralAnalysisRequest",
    "StructuralAnalysisResponse",
    "StructuralIssue",
    "VendorInfo",
    "ViolationDetail",
    "WarningDetail",
]
